### ISSUE TITLE
las ventanas emergentes no funcionan #2

### ISSUE THREAD

**Issue by lepton-gmbh** [JPro-one/JPro-Samples#2]
estoy intentando aplicacion helloJPro con maven, jdk11 , windows 10, netbeans 12.3

navegador arranca puerto 8080 y formas de colores girando pero no la app indicando. 
todo acorde JPro web instructions.  ¿a que puede ser debido?

java.lang.NullPointerException
[error] c.j.i.s.ViewSerializerActor - JavaFXStreamer - got Exception:
java.lang.ClassNotFoundException: com.jpro.hellojpro.App

**Comment by FlorianKirmaier** [comment]
Usually, the Ticket system is in English, but thanks to google translate, I'm still able to help you.

Which command do you use to start the sample? And which sample are you starting?
I've just tested one of the samples, and it works on my system. (`./gradlew popup:jproRun`)

**Comment by lepton-gmbh** [comment]
buenas tardes: 
muestra codigo descargado de su página de github. https://github.com/JPro-one/HelloJPro.git 

las 3 clases .java de gradle modelo  importadas como proyecto maven en com.jpro.hellojpro 

pom archivo: 
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.sandec.jpro</groupId>
    <artifactId>hellojpro-maven</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <properties>
        <jpro.version>2021.1.0</jpro.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>10</maven.compiler.source>
        <maven.compiler.target>10</maven.compiler.target>
        <javafx.version>15.0.1</javafx.version>
    </properties>

    <name>Hello JPro!</name>
    <url>https://www.jpro.one/</url>

    <build>

    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.1</version>
        </plugin>

        <plugin>
            <groupId>com.sandec.jpro</groupId>
            <artifactId>jpro-maven-plugin</artifactId>
            <version>${jpro.version}</version>
            <configuration>
                <visible>false</visible>
                <JVMArgs>
                    
                </JVMArgs>
                <mainClassName>com.jpro.hellojpro.App</mainClassName>
                <openingPath>/</openingPath>
            </configuration>
        </plugin>

    </plugins>
    </build>

    <pluginRepositories>
        <pluginRepository>
            <id>jpro - sandec repository</id>
            <url>https://sandec.jfrog.io/artifactory/repo</url>
        </pluginRepository>
    </pluginRepositories>

    <repositories>
        <repository>
            <id>jpro - sandec repository</id>
            <url>https://sandec.jfrog.io/artifactory/repo</url>
        </repository>
    </repositories>



    <dependencies>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-controls</artifactId>
            <version>${javafx.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-web</artifactId>
            <version>${javafx.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-swing</artifactId>
            <version>${javafx.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-fxml</artifactId>
            <version>${javafx.version}</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.openjfx</groupId>
            <artifactId>javafx-media</artifactId>
            <version>${javafx.version}</version>
            <scope>compile</scope>
        </dependency>

        <dependency>
            <groupId>com.sandec.jpro</groupId>
            <artifactId>jpro-webapi</artifactId>
            <version>2021.1.1</version>
            <type>jar</type>
        </dependency>
    </dependencies>

</project>

html: 
<!DOCTYPE html>

<html>
<head>
    <title>jpro Application: Hello JPro</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

    <link rel="stylesheet" type="text/css" href="/jpro/css/jpro-fullscreen.css">

    <link rel="stylesheet" type="text/css" href="/jpro/css/jpro.css">
    <script src="/jpro/js/jpro.js" type="text/javascript"></script>

</head>

<body>

<jpro-app href="/app/hellojpro" fullscreen="true"></jpro-app>

</body>

</html>

vamos, los de vuestra página de ejemplo. el jpro.conf el mismo. 
inicialmente intenter adaptar un proyecto a mi configuracion, pero al ver que solo salia navegador, repeti el tutorial de JPro docs create project paso a paso y no lo conseguí.   con conseguir clonar el helloworld Jpro me conformo.

**Comment by lepton-gmbh** [comment]
index.html quedo como se detalla. hubo un pequeño error de transcripcion en el anterior comentario. 

<!DOCTYPE html>

<html>
<head>
    <title>jpro Application: Hello JPro</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">

    <link rel="stylesheet" type="text/css" href="/jpro/css/jpro-fullscreen.css">

    <link rel="stylesheet" type="text/css" href="/jpro/css/jpro.css">
    <script src="/jpro/js/jpro.js" type="text/javascript"></script>

</head>

<body>

<jpro-app href="/app/hellojpro" fullscreen="true"></jpro-app>

</body>

</html>
 
y 

jpro.applications {
    //jpro apps
    "hellojpro" = com.jpro.hellojpro.HelloJProFXML
}

todo la carpeta raiz del proyecto. dicha carpeta tiene eso si un nombre distinto a JPro cuando me muevo por cmd hasta el y ejecuto  mvn jprorun

¿A que puede deberse?
saludos.

**Comment by FlorianKirmaier** [comment]
It would be great if you could post your next message in English.

It usually means, that the class com.jpro.hellojpro.App doesn't exist, or it doesn't extend javafx.application.Application.
You might wan't to change the mainclass in the pom.xml

There is a Hello World for JPro available, which works out of the box, which can be used as a starting point: https://github.com/JPro-one/HelloJPro-Maven

The jpro.conf is usually optional, so you should be able to skip it. It's only needed if you have multiple applications, and want to decide which one you want to start. In the index.html it can refer to the different names in the JProTag.

**Comment by lepton-gmbh** [comment]
Ok. it was great. i stayed for 3h with this. thx very much.
