### ISSUE TITLE
cmd gradlew jsproRun

### ISSUE THREAD

**Issue by sharad9** [JPro-one/JPro-Samples#5]
Starting a Gradle Daemon (subsequent builds will be faster)

* FAILURE: Build failed with an exception.
* 
* Where:
Settings file 'C:\Users\hp\Desktop\JPro-Samples-master\JPro-Samples-master\settings.gradle'

* What went wrong:
Could not compile settings file 'C:\Users\hp\Desktop\JPro-Samples-master\JPro-Samples-master\settings.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 61

  java.lang.IllegalArgumentException: Unsupported class file major version 61

**Comment by FlorianKirmaier** [comment]
I guess it's somehow JDK17 related.
We will update all projects, to the latest Gradle version with an additional GithubAction for JDK17.

**Comment by FlorianKirmaier** [comment]
JDK11 is recommended. But the fix for JD17 in this project will be available very soon.
For Gradle, it's recommended to just use the Gradle wrapper in the project. This way, you don't have to know which version is used.

**Comment by FlorianKirmaier** [comment]
It should work now, with the latest version of the repository. I'm closing the ticket now.
Feel free to create another ticket (With a better description), if you encounter another issue.

**Comment by sharad9** [comment]
**### _Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0._**
![2022-01-19-00-35-51](https://user-images.githubusercontent.com/59807761/150002469-658821bd-2396-4093-a029-a4775453a355.png)
![22022-01-19-00-40-06](https://user-images.githubusercontent.com/59807761/150002979-b76fcfe9-b411-48de-b3ac-1f37e0a77c8e.png)

**Comment by FlorianKirmaier** [comment]
Seems to be the following bug: https://discuss.gradle.org/t/unable-to-build-project-with-gradle-7-3-1-on-java-17/41601
Interestingly, it works for me.

**Comment by sharad9** [comment]
https://discuss.gradle.org/t/unable-to-build-project-with-gradle-7-3-1-on-java-17/41601/2
For whatever reason, the org.openjfx.javafxplugin plugin applies the org.javamodularity.moduleplugin.
It uses version 1.8.2 for that which has this bug: Build failure when using with Gradle 7.2 and Application plugin · Issue #199 · java9-modularity/gradle-modules-plugin · GitHub 31
It was fixed in 1.8.8, so if you also manually apply that plugin in a newer version (current is 1.8.10), then the error goes away.

**_### It is taking about org.javamodularity.moduleplugin._** , _**I cannot find it in build.gradle file**_ 
https://github.com/JPro-one/HelloJPro/blob/master/build.gradle   :(
""It uses version 1.8.2 for that which has this bug:""<---**_### Where is it located, in which file_**?

**Comment by FlorianKirmaier** [comment]
I've made a pull-request for the javafx-gradle-plugin: https://github.com/openjfx/javafx-gradle-plugin/pull/120
And I've added a workaround to the HelloJPro and JPro-Samples projects.
Can you verify, that it works now?

**Comment by sharad9** [comment]
Hurray  🥳🥳   Thanks You

@FlorianKirmaier 



![JPro Application_ default - Google Chrome 1_19_2022 6_48_17 PM](https://user-images.githubusercontent.com/59807761/150139009-c1f0b694-bac2-4aef-8389-669c60650d41.png)

**Comment by FlorianKirmaier** [comment]
Great to hear! I'm closing the ticket. 
Feel free to create a new ticket, if you encounter another problem.

**Comment by FlorianKirmaier** [comment]
You require the server, for it to work.
If you want to add it to an existing webpage, you might want to run the JPro Server on an own URL,
and embedd the component, as described here: https://www.jpro.one/docs/current/2.3/EMBEDDING_JPRO
